name: gsplat_env_test
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2.0.0
  - torchmetrics=1.7.1
  - pytorch
  - torchvision=0.21.0
  - pytorch-cuda=12.1 
  - scikit-learn
  - pip:
      - ninja
      - jaxtyping
      - rich
      - opencv-python
      - tqdm
      - pillow
      - tensorboard
      - matplotlib
      - pyyaml
      - viser
      - imageio[ffmpeg]
      - torchmetrics[image]
      - tyro>=0.8.8
      - tensorly
      - splines
      - gsplat
      - git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e
      - git+https://github.com/nerfstudio-project/nerfview@4538024fe0d15fd1a0e4d760f3695fc44ca72787
